--!strict
if game:GetService("RunService"):IsServer() then
	return {}
end
local _CinematicClass = require(script._CinematicClass)
export type Cinematic = _CinematicClass.Cinematic
export type CinematicStartArgs = _CinematicClass.CinematicStartArgs

local _Icon = require(script._Icon)
export type Icon = _Icon.Icon

local _GuiButtonClass = require(script._GuiButtonClass)
export type WrappedGuiButton = _GuiButtonClass.WrappedGuiButton

local _GuiImageClass = require(script._GuiImageClass)
export type WrappedGuiImage = _GuiImageClass.WrappedGuiImage

local _GuiObjectClass = require(script._GuiObjectClass)
export type WrappedGuiObject = _GuiObjectClass.WrappedGuiObject

local _GuiStrokeClass = require(script._GuiStrokeClass)
export type WrappedGuiStroke = _GuiStrokeClass.WrappedUiStroke

local _GuiTextClass = require(script._GuiTextClass)
export type WrappedTextLabel = _GuiTextClass.WrappedTextLabel

local _SurfaceGuiClass = require(script._SurfaceGuiClass)
export type WrappedSurfaceGui = _SurfaceGuiClass.WrappedSurfaceGui

local _BillboardGuiClass = require(script._BillboardGuiClass)
export type WrappedBillboardGui = _BillboardGuiClass.WrappedBillboardGui

local _EasyVisuals = require(script._EasyVisuals)
export type InterfaceEffect = _EasyVisuals.InterfaceEffect

local _LightningEffects = require(script._LightningEffects)
export type LightningBolt = _LightningEffects.LightningBolt
export type LightningSparks = _LightningEffects.LightningSparks
export type LightningExplosion = _LightningEffects.LightningExplosion

local _ParallaxWindows = require(script._ParallaxWindows)
export type ParallaxWindow = _ParallaxWindows.ParallaxWindow

local _Streamable = require(script._Streamable)
export type StreamableType = _Streamable.StreamableType

local _StreamableUtil = require(script._StreamableUtil)

local _WindLineCreator = require(script._WindLineCreator)
export type WindLineCreator = _WindLineCreator.WindLineCreator
export type WindLineCreatorParams = _WindLineCreator.WindLineCreatorParams

local _WindShake = require(script._WindShake)
export type WindShakeSettings = _WindShake.WindShakeSettings

local _Input = require(script._Input)
export type GamepadType = _Input.GamepadType
export type MouseType = _Input.MouseType
export type KeyboardType = _Input.KeyboardType
export type TouchType = _Input.TouchType

local _Screen3D = require(script._Screen3D)
export type screen3D = _Screen3D.screen3D
export type screenGen = _Screen3D.screenGen
export type component3D = _Screen3D.component3D
export type componentGen = _Screen3D.componentGen

return {
	Screen3D = _Screen3D,
	CinematicClass = _CinematicClass,
	Icon = _Icon,
	GuiButtonClass = _GuiButtonClass,
	GuiImageClass = _GuiImageClass,
	GuiObjectClass = _GuiObjectClass,
	GuiStrokeClass = _GuiStrokeClass,
	GuiTextClass = _GuiTextClass,
	SurfaceGuiClass = _SurfaceGuiClass,
	BillboardGuiClass = _BillboardGuiClass,
	EasyVisuals = _EasyVisuals,
	LightningEffects = _LightningEffects,
	ParallaxWindows = _ParallaxWindows,
	Streamable = _Streamable,
	StreamableUtil = _StreamableUtil,
	WindLineCreator = _WindLineCreator,
	WindShake = _WindShake,
	Input = _Input,
}
