--[[local replicatedStorage = game:GetService("ReplicatedStorage")

local replicasFolder = replicatedStorage.Modules.Client.Replicas

local itemReplica = require(replicasFolder.ItemReplica)
local chestReplica = require(replicasFolder.ChestReplica)

export type ItemReplicaClassType = itemReplica.ClassType
export type ChestReplicaClassType = chestReplica.ClassType

local a = {} :: itemReplica.ClassType

a:
]]


return {}